[workspace]
members = ["pixel_zero", "launcher"]
resolver = "3"

[workspace.lints.clippy]
pedantic = "warn"

[workspace.dependencies]
pixel_zero = { path = "pixel_zero" }
anyhow = "1.0"
glam = "0.30"
log = { version = "0.4", features = ["std"] }
thiserror = "2.0"
